### ISSUE TITLE
the problem when Key of the struct is the same 

### ISSUE THREAD

**Issue by alihossein** [HuKeping/rbtree#36]
thanks for this package . 

I think we get into trouble when the key (**Expiry**) is the same. So only one of the nodes is inserted.

```
package main

import (
	"fmt"
	"github.com/HuKeping/rbtree"
	"time"
)

type Var struct {
	Expiry time.Time `json:"expiry,omitempty"`
	ID     string    `json:"id",omitempty`
}

// We will order the node by `Time`
func (x Var) Less(than rbtree.Item) bool {
	//return x.Expiry.Before(than.(Var).Expiry)
	return x.Expiry.Before(than.(Var).Expiry) 
}

func main() {
	rbt := rbtree.New()

	ex :=time.Now().Add(time.Second * 10)
	var1 := Var{
		Expiry: ex,
		ID:     "var1",
	}
	var2 := Var{
		Expiry: ex,
		ID:     "var2",
	}
	var3 := Var{
		Expiry: ex,
		ID:     "var2-dup",
	}
	var4 := Var{
		Expiry: ex,
		ID:     "var4",
	}
	var5 := Var{
		Expiry: ex,
		ID:     "var5",
	}

	rbt.Insert(var1)
	rbt.Insert(var2)
	rbt.Insert(var3)
	rbt.Insert(var4)
	rbt.Insert(var5)

	tmp := Var{
		Expiry: var4.Expiry,
		ID:     "This field is not the key factor",
	}

	result:=rbt.Get(tmp)
	fmt.Println("Len is :" , rbt.Len()) // print 1 
	fmt.Println(result)

}


```

If I changed the condition, all nodes add successfully, but the **Get** method did not work, and the result is nill!

```
package main

import (
	"fmt"
	"github.com/HuKeping/rbtree"
	"time"
)

type Var struct {
	Expiry time.Time `json:"expiry,omitempty"`
	ID     string    `json:"id",omitempty`
}

// We will order the node by `Time`
func (x Var) Less(than rbtree.Item) bool {
	//return x.Expiry.Before(than.(Var).Expiry)
	return x.Expiry.Before(than.(Var).Expiry) || x.Expiry.Equal(than.(Var).Expiry)
}

func main() {
	rbt := rbtree.New()

	ex :=time.Now().Add(time.Second * 10)
	var1 := Var{
		Expiry: ex,
		ID:     "var1",
	}
	var2 := Var{
		Expiry: ex,
		ID:     "var2",
	}
	var3 := Var{
		Expiry: ex,
		ID:     "var2-dup",
	}
	var4 := Var{
		Expiry: ex,
		ID:     "var4",
	}
	var5 := Var{
		Expiry: ex,
		ID:     "var5",
	}

	rbt.Insert(var1)
	rbt.Insert(var2)
	rbt.Insert(var3)
	rbt.Insert(var4)
	rbt.Insert(var5)

	tmp := Var{
		Expiry: var4.Expiry,
		ID:     "This field is not the key factor",
	}

	result:=rbt.Get(tmp)
	fmt.Println("Len is :" , rbt.Len()) // print 5
	fmt.Println(result)  // print nil


}


```

**Comment by HuKeping** [comment]
@alihossein it's intentional,  this implementation does not support `duplicate keys`, should red-black tree support `duplicate keys`?

**Comment by HuKeping** [comment]
FYI: 

http://grail.cba.csuohio.edu/~lin/cis506/Chapt9.pdf

Chapter #Duplicate Keys

**Comment by alihossein** [comment]
OK.
So duplicate data is allowed in RBTree but you have ignored it in your implementation. it's true?

**Comment by HuKeping** [comment]
Not exactly, I think R-B trees are  not designed for data structures which support duplicates, but rather sets. So this implementation would not support duplicate keys.

Maybe I should add a clarification to README

**Comment by alihossein** [comment]
> Maybe I should add a clarification to README

yes, I think it is better  :+1:

**Comment by MeteorsLiu** [comment]
Update in 2025:

I implemented a duplicate keys supported RBTree.


[https://github.com/MeteorsLiu/rbtree](https://github.com/MeteorsLiu/rbtree)

More instructions about it:
https://zhuanlan.zhihu.com/p/20372767336

RBTree allows duplicate keys, which means we need to implement it, that's what i thought.

What's more, it's quite common to use duplicate  keys in RBTree, the most famous case is Linux CFS.

**Comment by HuKeping** [comment]
I checked `rb_find_add()`  of Linux, seems not allowed duplicated tree.

And even if two tasks have the same vruntime, CFS will distinguish them through other means (such as task priority or scheduling policies) rather than relying on duplicate key support in the red-black tree.

Please correct me if i'm wrong.

**Comment by HuKeping** [comment]
> Update in 2025:
> 
> I implemented a duplicate keys supported RBTree.
> 
> https://github.com/MeteorsLiu/rbtree
> 
> More instructions about it: https://zhuanlan.zhihu.com/p/20372767336
> 
> RBTree allows duplicate keys, which means we need to implement it, that's what i thought.
> 
> What's more, it's quite common to use duplicate keys in RBTree, the most famous case is Linux CFS.

I checked `rb_find_add()` of Linux, seems not allowed duplicated tree.

And even if two tasks have the same vruntime, CFS will distinguish them through other means (such as task priority or scheduling policies) rather than relying on duplicate key support in the red-black tree.

Please correct me if i'm wrong.

**Comment by MeteorsLiu** [comment]
> > Update in 2025:
> > I implemented a duplicate keys supported RBTree.
> > https://github.com/MeteorsLiu/rbtree
> > More instructions about it: https://zhuanlan.zhihu.com/p/20372767336
> > RBTree allows duplicate keys, which means we need to implement it, that's what i thought.
> > What's more, it's quite common to use duplicate keys in RBTree, the most famous case is Linux CFS.
> 
> I checked `rb_find_add()` of Linux, seems not allowed duplicated tree.
> 
> And even if two tasks have the same vruntime, CFS will distinguish them through other means (such as task priority or scheduling policies) rather than relying on duplicate key support in the red-black tree.
> 
> Please correct me if i'm wrong.


Your conclusion is not wrong, it doesn't allow duplicate keys for sure.

However, the code you mentioned is not CFS algorithm, that's EEVDF algorithm which is based on CFS and replaces CFS after linux kernel 6.6.

Related code about CFS using duplicate keys:

https://elixir.bootlin.com/linux/v5.1.21/source/kernel/sched/fair.c#L550

Thanks for your reply, BTW, happy Chinese new year!
